### ISSUE TITLE
Crafting tables?

### ISSUE THREAD

**Issue by nightyngale** [FaeCraft/SakuraRosea#10]
The "Sakura Crafting Table" added by the mod shows up in REI, but isn't craftable (4 sakura planks gives you a regular crafting table), and when spawned in via commands, the block drops nothing when broken. (This is happening on Fabric 1.16.4.) I did notice they're not included in your preview image, though, so I apologize if you haven't gotten around to implementing them yet. They're really cute, so I look forward to seeing them in the future!

**Comment by gdude2002** [comment]
Hey, thanks for the issue!

Crafting recipes can be a little tricky when it comes to some items - since we add a new wood, and that wood is correctly tagged as wood, vanilla wants to use it to craft a vanilla table. We do include a recipe in there for our table - for the time being, you can install [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric) to get access to that recipe.

I would like to see this problem fixed, though - I'll look into it more.

**Comment by gdude2002** [comment]
Looking into this further, it appears that Minecraft's recipe priority order is quite broken. The order in which recipes are picked appears to be essentially random - which means that, depending on the mods you have loaded, you may get our recipe or the vanilla one. It's hard to tell when, exactly.

Some mods solve this by changing the order Minecraft searches through recipes so that it prefers all modded recipes over vanilla ones. For this reason, installing some mods - How The Crafting Has Tabled or BetterNether for example - means you'll always get the correct recipe.

I'll need to look into this further, as I don't particularly like that solution. However, if it's the only way that'll work, I'll do it.

**Comment by gdude2002** [comment]
This will be solved in the next release. Thanks for making the issue!
